CRITICAL — URL PRESERVATION:
- When converting citation markers, ONLY convert the marker itself (e.g., "[1]" or "(Ref. 1)")
- DO NOT remove or modify any text that follows the citation marker, including URLs
- If a citation marker is followed by "https:" or a URL, wrap the URL in parentheses
- When a citation superscript (¹, ², ³, …) or a closing parenthesis is immediately followed by a parenthesized URL, insert a single space before the opening parenthesis.
- Examples:
  - "[1]https://example.com" → "¹(https://example.com)" (URL in parentheses)
  - "[1]https:" → "¹(https:)" (URL prefix in parentheses)
  - "Text [1]https://example.com more text" → "Text ¹(https://example.com) more text" (URL in parentheses)
  - "(Ref. 1) https://example.com" → "¹ (https://example.com)" (URL in parentheses with space)
  - "[1]http://example.com" → "¹(http://example.com)" (URL in parentheses)
  - "²(https://example.com)" → "² (https://example.com)" (space before opening paren)
  - ")²(https://a.com)(https://b.com)" → ")² (https://a.com) (https://b.com)" (space before each parenthesized URL)
